# Generated by Django 3.0.5 on 2020-04-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200405_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseregistration',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
