# Generated by Django 3.0.5 on 2020-04-04 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('matric_no', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='students')),
                ('dept', models.CharField(blank=True, max_length=255, verbose_name='Your Department')),
                ('school', models.CharField(blank=True, max_length=255, verbose_name='Name of school')),
                ('level', models.CharField(blank=True, choices=[('100', '100L'), ('200', '200L'), ('300', '300L'), ('400', '400L'), ('500', '500L'), ('600', '600L')], max_length=4, verbose_name='Your Level')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], max_length=6)),
                ('qualification', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lecturer',
                'verbose_name_plural': 'Lecturers',
            },
        ),
    ]
