# Generated by Django 3.0.5 on 2020-04-15 14:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200413_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='dept',
            field=models.CharField(blank=True, max_length=255, verbose_name='Your Department'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lecturers'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='school',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name of school'),
        ),
    ]
